services:

  selenium:
    image: selenium/standalone-chrome:95.0-20250717
    container_name: selenium
    hostname: selenium
    shm_size: 2g
    ports:
    - 7900:7900
    networks:
    - agentes-conversacionais

networks:
  agentes-conversacionais:
    external: true
